[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tabclustpfn"
version = "0.1.0"
description = "TabClustPFN local package"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["configs*", "datasets*", "exp*", "model*", "prior*", "utils*"]
